name: cropcaster

services:
  postgres:
    image: postgres:15-alpine
    container_name: cropcaster_n8n_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_POSTGRESDB_DATABASE}
      POSTGRES_USER: ${DB_POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRESDB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  n8n:
    build: .
    image: cropcaster:latest
    container_name: cropcaster_n8n
    env_file:
      - .env
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./scripts:/scripts
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  n8n_data:
  postgres_data:
